sudo: false

language: c

compiler:
  - gcc

git:
  submodules: false

addons:
  apt:
    packages:
      - p7zip-full
      - docutils-common
      - docutils-doc
      - docbook
      - docbook-xml
      - docbook-xsl
      - xsltproc

env:
  global:
    - secure: "DC12OV65iyBzELywj19yI4S8DmmBmZO8hbT3Iq0kJ4yo0aMQzzJDsVpmm2Jwk/Qf/yLyBsAhkpanScJJ9eEekmK8OZN8H9EJ1kgai58IWk0gWKKzJ0lyQH/vsYEyfxCSwqejoIdd07nQh5B/1L5Th3I2vLT2udHUPU2Np/MKgUw="
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - env: STATUS_TESTS=true
    - env: RELEASE_BUILD=LF
    - env: RELEASE_BUILD=CRLF

before_install:
  - |
    export "BOOST_BUILD_DIR=${TRAVIS_BUILD_DIR}/../build"
    cd "${TRAVIS_BUILD_DIR}/.."
    wget -O rapidxml.zip http://sourceforge.net/projects/rapidxml/files/latest/download
    unzip -n -d rapidxml rapidxml.zip
    export RAPIDXML=`ls -1d ${PWD}/rapidxml/rapidxml-*`

before_script:
  - |
    set -e # Fail the whole script whenever any command fails
    if [[ "${STATUS_TESTS}" == "true" ]]; then
      cd "${TRAVIS_BUILD_DIR}"
      git submodule update --init --recursive
    fi
  - |
    if [[ "${RELEASE_BUILD}" == "LF" ]]; then
      cd "${TRAVIS_BUILD_DIR}"
      git config core.eol lf
      git config core.autocrlf false
      git rm --cache -r .
      git reset --hard HEAD
      git submodule update --init --recursive
    fi
  - |
    if [[ "${RELEASE_BUILD}" == "CRLF" ]]; then
      cd "${TRAVIS_BUILD_DIR}"
      git config core.eol crlf
      git config core.autocrlf false
      git rm --cache -r .
      git reset --hard HEAD
      git submodule update --init --recursive
    fi

script:
  - |
    if [[ "${STATUS_TESTS}" == "true" ]]; then
      cd "${TRAVIS_BUILD_DIR}"
      ./bootstrap.sh
      ./b2 -n
      cd status
      ../b2 -n -d0
    fi
  - |
    if [[ "${RELEASE_BUILD}" == "LF" || "${RELEASE_BUILD}" == "CRLF" ]]; then
      mkdir -p "${BOOST_BUILD_DIR}/dist/bin"
      export "PATH=${BOOST_BUILD_DIR}/dist/bin:${PATH}"
      cd "${TRAVIS_BUILD_DIR}/tools/build"
      ./bootstrap.sh
      cp -p b2 "${BOOST_BUILD_DIR}/dist/bin/b2"
      git clean -dfqx
      cd "${TRAVIS_BUILD_DIR}"
      b2 -q headers
      cd "${TRAVIS_BUILD_DIR}/libs/geometry/doc/src/docutils/tools/doxygen_xml2qbk"
      b2 -a -q --build-dir="${BOOST_BUILD_DIR}" --distdir="${BOOST_BUILD_DIR}/dist"
      cd "${TRAVIS_BUILD_DIR}/libs/geometry"
      git clean -dfqx
      cd "${TRAVIS_BUILD_DIR}/tools/quickbook"
      b2 -q --build-dir="${BOOST_BUILD_DIR}" --distdir="${BOOST_BUILD_DIR}/dist"
      git clean -dfqx
      echo "using quickbook : \"${BOOST_BUILD_DIR}/dist/bin/quickbook\" ;" >> "${HOME}/user-config.jam"
      cd "${TRAVIS_BUILD_DIR}/tools/auto_index/build"
      b2 -q --build-dir="${BOOST_BUILD_DIR}" --distdir="${BOOST_BUILD_DIR}/dist"
      cd "${TRAVIS_BUILD_DIR}/tools/auto_index"
      git clean -dfqx
      echo "using auto-index : \"${BOOST_BUILD_DIR}/dist/bin/auto_index\" ;" >> "${HOME}/user-config.jam"
    fi
  - |
    if [[ "${RELEASE_BUILD}" == "LF" || "${RELEASE_BUILD}" == "CRLF" ]]; then
      cd "${TRAVIS_BUILD_DIR}/.."
      wget "https://raw.githubusercontent.com/boostorg/release-tools/develop/MakeBoostDistro.py"
      chmod +x MakeBoostDistro.py
      export BOOST_RELEASE=boost_${TRAVIS_BRANCH}_${TRAVIS_COMMIT}
      ./MakeBoostDistro.py "${TRAVIS_BUILD_DIR}" "${BOOST_RELEASE}"
    fi
  - |
    if [[ "${RELEASE_BUILD}" == "LF" ]]; then
      cd "${TRAVIS_BUILD_DIR}/.."
      tar -zcf "${BOOST_RELEASE}.tar.gz" "${BOOST_RELEASE}"
      tar -cjf "${BOOST_RELEASE}.tar.bz2" "${BOOST_RELEASE}"
      ls -la
    fi
  - |
    if [[ "${RELEASE_BUILD}" == "CRLF" ]]; then
      cd "${TRAVIS_BUILD_DIR}/.."
      zip -qr "${BOOST_RELEASE}.zip" "${BOOST_RELEASE}"
      7z a -r "${BOOST_RELEASE}.7z" "${BOOST_RELEASE}" > /dev/null
      ls -la
    fi

after_success:
  - |
    if [[ "${RELEASE_BUILD}" == "LF" ]]; then
      cd "${TRAVIS_BUILD_DIR}/.."
      curl -v -T "${BOOST_RELEASE}.tar.gz" "-ugrafikrobot:${BINTRAY}" "https://api.bintray.com/content/boostorg/snapshots/${TRAVIS_BRANCH}/${TRAVIS_COMMIT}/${BOOST_RELEASE}.tar.gz?publish=1"
      curl -v -T "${BOOST_RELEASE}.tar.bz2" "-ugrafikrobot:${BINTRAY}" "https://api.bintray.com/content/boostorg/snapshots/${TRAVIS_BRANCH}/${TRAVIS_COMMIT}/${BOOST_RELEASE}.tar.bz2?publish=1"
    fi
  - |
    if [[ "${RELEASE_BUILD}" == "CRLF" ]]; then
      cd "${TRAVIS_BUILD_DIR}/.."
      curl -v -T "${BOOST_RELEASE}.zip" "-ugrafikrobot:${BINTRAY}" "https://api.bintray.com/content/boostorg/snapshots/${TRAVIS_BRANCH}/${TRAVIS_COMMIT}/${BOOST_RELEASE}.zip?publish=1"
      curl -v -T "${BOOST_RELEASE}.7z" "-ugrafikrobot:${BINTRAY}" "https://api.bintray.com/content/boostorg/snapshots/${TRAVIS_BRANCH}/${TRAVIS_COMMIT}/${BOOST_RELEASE}.7z?publish=1"
    fi
